module.exports = {
  apps: [
    {
      name: "remotage-backend",
      cwd: "/var/www/remotage/backend",
      script: "node",
      args: "dist/server.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      env_production: {
        NODE_ENV: "production",
        PORT: 5000,
      },
      error_file: "/var/log/remotage/backend-error.log",
      out_file: "/var/log/remotage/backend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "remotage-frontend",
      cwd: "/var/www/remotage/frontend",
      script: "node_modules/.bin/next",
      args: "start -p 3000",
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      env_production: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "/var/log/remotage/frontend-error.log",
      out_file: "/var/log/remotage/frontend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};